### ISSUE TITLE
Configure renv to use the GRAN Repository?

### ISSUE THREAD

**Issue by uzpaka** [CredibilityLab/groundhog#120]
Hello,

I am currently using renv for managing R package dependencies in my project. However, I am often encountering issues when running renv::restore() because some older packages do not have binaries available in the default repositories.

Is there a way to configure renv to use the GRAN repository provided by Groundhog for sourcing package binaries?

**Comment by urisohn** [comment]
i think that's an issue for {renv} developers to figure out.
GRAN is an open S3 repo, so they can access the binaries and the list of binaries.

https://gran.groundhogr.com/ 

I suspect the issue may be compatibility of your version of R and binaries thought, since Posit does have its own archive, so if GRAN has it, it's likely that posit has it too? I don't know.  Again, i can help with groundhog but not with renv.
