### ISSUE TITLE
Add check about groundhogR version at startup

### ISSUE THREAD

**Issue by Bisaloo** [CredibilityLab/groundhog#23]
As requested by email: add a check when groundhogR is started to verify if users are users the latest version and display a message if not.

**Comment by urisohn** [comment]
i think we have to add this prior to 1st release so that when there is a 2nd release, people with the first will be notified.

**Comment by urisohn** [comment]
Since it looks likely that will do a more private initial release, before CRAN, i would suggest including the version check, for now, against something on the groundhogR.com server. So say we do 1.0.1 the day after sharing the paackage with people, by the time the 5th person tests it, they are already told to update.

here is how i think i would implement it.

when grondhog.library() runs, it looks for a file in the groundhog.folder called groundhogR.newest.version.

that file is a single string with the newest version, so 1.0.0 to start

If the number is bigger than the current version of groundhog, a message popsup telling them to update by runningL
install.packages("http://goundhogR.com/1.0.1.tar.gz", repos=NULL)
or whatever it may be.

Also, if the file is more than 2 hours old, it is automatically updated by lookup the tar.ball with the highest # in groundhogR.com

How does this sound?

**Comment by Bisaloo** [comment]
Another option is to fetch the package source from the server, check if the content has been modified (there are very efficient built-in methods to do this) and if so, prompt the user.

**Comment by urisohn** [comment]
oh, nice, e.g., comparing checksum for local vs server ones?

**Comment by Bisaloo** [comment]
yes, the md5 checksums are included in R package sources

**Comment by Bisaloo** [comment]
A first version of this for CRAN was added in d4348f2 if you want to have a look
