### ISSUE TITLE
Pushing cran.toc.rds corrections

### ISSUE THREAD

**Issue by urisohn** [CredibilityLab/groundhog#54]
an issue relating to two issues that came up today (update of cran.toc.rds and corrupt lines in that file):

It would be nice from the server side to push updates if something is discovered to be wrong.

So imagine we had groundhog go live 2 months ago and today we realize some entries in cran.toc.rds are corrupt. It would be nice to force an update for everyone 

**An easy solution **
We put a file on groundhogr..com, a simpel text file, with just a date in it, it has the date of the last time an issue was discovered and corrected. When a user loads groundhog, if they have n internet connection, it checks that file. If it contains a date that is more recent than the most recent date in their cran.toc.rds, they get it updated.
This means we can push an update on all users if we find a problem with cran.toc.rds which i think inevitably it will happen at some point.

**Comment by Bisaloo** [comment]
The most future-proof solution would be to use semantic versioning for the data.

Minor version numbers would indicate an error and that users need to update, as you suggest in this error.

Major version numbers would indicate breaking changes in case we ever need to change the format. So that multiple versions of groundhog, using different formats, can co-exist at the same time.

**Comment by urisohn** [comment]
Had missed this. 
So the cran.toc.rds would become
cran.toc.1.0.rds?
