### ISSUE TITLE
Why do edits lead to these errors?

### ISSUE THREAD

**Issue by urisohn** [CredibilityLab/groundhog#55]
![image](https://user-images.githubusercontent.com/56013245/99181855-8e58d800-2731-11eb-8c60-790f5a9a5087.png)

**Comment by Bisaloo** [comment]
Because there was a recent change in the digest package that is used to run the tests. It now requires R >= 3.3.0 (https://cran.r-project.org/package=digest). This does not mean that groundhog is broken in any way, just that the tools we use to run the tests don't work. I planned on checking how to run simple tests without these packages (it would allow us to test all R versions starting from 3.0.0) but I didn't get the time yet.
