### ISSUE TITLE
Rmarkdown render ends in interrupted execution

### ISSUE THREAD

**Issue by FONDECYTACC** [CredibilityLab/groundhog#63]
I try to run an .rmd extension with groundhog.library but I get the message "execution interrupted".

**Comment by urisohn** [comment]
May this be Issue #2 here: http://groundhogr.com/troubleshooting
If it is, it is caused by RStudio loading, without notifying you, current versions of package which you want to load different versions of. 

If that is not it, could you say a bit more about what you were executing and the full output in the console that you got?

**Comment by urisohn** [comment]
An update is that the groundhog 1.3, in development, will be more robust to packages loaded automatically by R Studio
