### ISSUE TITLE
Problem installing packages : "does not look like a tar archive"

### ISSUE THREAD

**Issue by ClaudiaNdf** [CredibilityLab/groundhog#72]
When running `groundhog.library()` I repeatedly get confronted with an the error message: 
```
1) Installing: data.table_1.14.0
/usr/bin/tar: This does not look like a tar archive
/usr/bin/tar: Skipping to next header
/usr/bin/tar: Exiting with failure status due to previous errors

The package 'data.table_1.14.0' failed to install!
```
This is just an example, I get this message for every package that is to be installed.
Strangely, no tar archives are downloaded, but .zip archives:

```
groundhog says: will now download 42 binary packages from CRAN
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/data.table_1.14.0.zip'
Content type 'application/zip' length 2602906 bytes (2.5 MB)
downloaded 2.5 MB
```

 Might that be part of the problem?

-----

> > sessionInfo()
> R version 4.1.0 (2021-05-18)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
> [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] groundhog_1.4.0
> 
> loaded via a namespace (and not attached):
> [1] colorspace_2.0-2 scales_1.1.1     compiler_4.1.0   R6_2.5.0         tools_4.1.0      lifecycle_1.0.0 
> [7] munsell_0.5.0    rlang_0.4.11

**Comment by urisohn** [comment]
Hi, i am traveling so limited ability to dive into this, but couple of clarifications.
1. Which date (groundhog.day) are you using?
2. Are you indeed using a Windows Server 2008 OS?
3. Are you trying to load data.table?
4. Are you able to load any packages with groudhog?
5.

**Comment by ClaudiaNdf** [comment]
Hi,
I was trying to install the following packages und dates:
```
grnd_pckgs <- c( "eatGADS", "beepr", "mice")
groundhog_day <- "2021-07-25"
```
`data.table` is just a dependency. I've tried other packages, but I get the same. This additional warning message:
```
1: In utils::untar(infile, exdir = outfile) :
  ‘tar.exe -xf "C:/Users/neuendcl/Documents/R_groundhog/groundhog_library//temp/audio_0.1-7.zip" -C "C:/Users/neuendcl/Documents/R_groundhog/groundhog_library//R-4.1/audio_0.1-7"’ returned error code 2
```
Yes, I guess I am using Windows Server 2008 OS (it is a university server for intensive calculations).

**Comment by urisohn** [comment]
Hi Claudia, seems like Windows 2008 is no longer supported by Microsoft which would make testing this through a virtual machine more difficult and less valuable. Could you test those same commands on your personal laptop? if they work, they i think for now at least i would say groundhog is not compatible with windows 2008, Come September I may give it another look. But, if you run into issues even with your own laptop using an up-to-date operating system I will try to provide faster assistance.

**Comment by urisohn** [comment]
A user with Windows 10 experienced the same issue. I was also unable to reproduce it.
It is in my to do list to spot the source of this bug. Hopefully in early September.
In the meantime, it seems like installing from source is a way to bypass the problem. So adding the option force.source=TRUE
I added this to the troubleshooting page in https://groundhogr.com/troubleshooting

**Comment by ClaudiaNdf** [comment]
Hi Uri, 
thanks for reminding me - in the meantime I was able to test the same call on another system - in windows 10 it is working fine for me. 

The force.source workaround works for me, in general, although there are some packages for which it fails, but I guess that is due to these packages (the warning "this package has a configure script, It probably needs manual configuration" pops up). I have adapted my code to install those packages separately, if needed.

Thanks for your endeavor to increase reproducibility and make science better :)
Claudia

**Comment by urisohn** [comment]
Hi Claudia

I know you closed the issue, but I am trying to provide a real solution 
rather than a work around.
The other person who had an issue was using an older version of Windows 
10, so I came up with a hypothesis that could explain the problems based 
on an antiquated OS. I made some changes in the developmental version of 
groundhog that would address the problem if it is the actual root 
source.

Would you be willing to try the developmental version of groundhog in 
the Windows 2008 server? I don't have access to an older Windows machine 
to test this, if you can do it, it involves the following:

#Install the dev version of groundhog
      
install.packages("http://groundhogr.com/groundhog_1.4.0.9001.tar.gz",repos=NULL,type='source')

to make sure you load the newly installed version you should restart 
your R session (CRTL-SHFT-F10)

Then
     library('groundhog')
     groundhog.library(pkg ,  '2021-08-15');

  #use a package you have not installed with groundhog before, say 'AER', 
or 'pwr' , or 'metafor' or any package you don't have so that it has to 
install it.

(when you load groundhog it will tell you which version it is, is should 
say 1.4.0.9004)

To go back to using the version of groundhog on CRAN you just install it 
again
install.packages('groundhog')

If you can't do it i obviously fully understand,

Thanks either way,

Uri


------ Original Message ------
From: "Claudia Neuendorf" ***@***.***>
To: "CredibilityLab/groundhog" ***@***.***>
Cc: "Uri Simonsohn" ***@***.***>; "Comment" 
***@***.***>
Sent: 8/19/2021 6:59:48 AM
Subject: Re: [CredibilityLab/groundhog] Problem installing packages : 
"does not look like a tar archive" (#72)

**Comment by ClaudiaNdf** [comment]
Hi Uri,
thanks for getting back to me. I have tried out the syntax you suggested, with developmental version 1.4.9004 (the path including 1.4.9001 didn't work. Maybe it was a typo?). It works perfectly fine with this version of groundhog. I successfully installed the metafor package and also my own project's packages installed beautifully.
Will the solution be implemented in the next groundhog release?
Best regards,
Claudia

**Comment by urisohn** [comment]
Hi Claudia,

Wonderful. Glad, you caught and fixed that typo.
Yes, this fix will be included in the next release, possibly next week, 
but almost surely by mid-September.
There is one more minor bug i want to look into and then go through the 
process of updating on CRAN.

When you load groundhog it always checks if a newer version is 
available, so you will know when it is available

Thanks for alerting me to this and for testing the solution

Uri

------ Original Message ------
From: "Claudia Neuendorf" ***@***.***>
To: "CredibilityLab/groundhog" ***@***.***>
Cc: "Uri Simonsohn" ***@***.***>; "Comment" 
***@***.***>
Sent: 8/22/2021 11:24:42 PM
Subject: Re: [CredibilityLab/groundhog] Problem installing packages : 
"does not look like a tar archive" (#72)
